def label = "python"
podTemplate(label: label, containers: [
containerTemplate(name: 'python', image: 'python:3-alpine', ttyEnabled: true, command: 'cat', envVars: [envVar(key: 'VERSION', value: '1.0.0')]),
]) {
    node(label) {
        stage('Run python') {
            //sh 'python docker/zip_job.py'
            git changelog: false, poll: false, url: 'https://github.com/evyatare92/tufin.git'
            sh 'python --version'
            sh 'python docker/zip_job.py'
            //sh 'cd tufin'
            
        }
    }
}