def label = "python"
podTemplate(label: label, containers: [
containerTemplate(name: 'python', image: 'python:3-alpine', ttyEnabled: true, command: 'cat', resourceLimitCpu: '500m', resourceLimitMemory: '512Mi'),
]) {
    node(label) {
        stage('Run python') {
            //sh 'python docker/zip_job.py'
            git changelog: false, poll: false, url: 'https://github.com/evyatare92/tufin.git'
            sh 'cd tufin'
            sh 'ls'
        }
    }
}